--- 
configFile: ~
framework: jest
postMerge: 
  pattern: 
    - "./packages/**/test/*.test.{ts,tsx}"
postRun: 
  command: 
    - "node --version"
preMerge: 
  pattern: 
    - "./packages/**/test/*.test.{ts,tsx}
preRun: 
  command: 
    - "yarn install"
    - "yarn build"
    - "yarn run"
version: 1.0
