---
framework: jest
preRun:
  command:
    - yarn install
    - yarn build
    - yarn run
postMerge:
  pattern:
    - "./packages/**/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
preMerge:
  pattern:
    - "./packages/**/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
postRun:
  command:
    - node --version
configFile: jest.config.js
version: 1.0
