---
framework: jest
licenseTier: xsmall
postMerge: 
  pattern: 
    - "./packages/core/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./packages/core/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.1
