---
framework: jest
blocklist:
  - "./src/calculator.test.js##Blacklist a test"
  - "./src/newFileTest.test.js##Comparision tests"
licenseTier: xsmall
postMerge: 
  pattern: 
    - "./packages/**/*.test.ts"
    - "./packages/**/*.test.tsx"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./packages/**/*.test.ts"
    - "./packages/**/*.test.tsx"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.1