---
framework: jest     
preRun:
  command:
    - yarn install 
preMerge:
  pattern:
    - "./packages/core/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
postMerge:
  pattern: 
    - "./packages/core/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
postRun:
  command:
    - yarn --version
version: 1.0
